hmrc/deregister-vat-frontend

app/controllers/ErrorsController.scala, app/controllers/HelloWorldController.scala, app/views/errors/sessionTimeout.scala.html, app/views/errors/unauthorised.scala.html, app/views/helloworld/hello_world.scala.html, build.sbt, conf/logback.xml, test/controllers/ErrorsControllerSpec.scala, test/controllers/HelloWorldControllerSpec.scala, test/views/ViewBaseSpec.scala, test/views/errors/SessionTimeoutSpec.scala, test/views/errors/UnauthorisedViewSpec.scala
Also changed logging levels to reduce noise and fixed a scala sbt warning
=> Refactored view and controller parameters, upgraded frontend-bootstrap

README.md, app/testOnly/controllers/FeatureSwitchController.scala, app/testOnly/forms/FeatureSwitchForm.scala, app/testOnly/models/FeatureSwitchModel.scala, app/testOnly/views/featureSwitch.scala.html, build.sbt, conf/app.routes, conf/application-json-logger.xml, conf/logback-test.xml, conf/testOnlyDoNotUseInAppConf.routes, it/helpers/CustomMatchers.scala, it/helpers/IntegrationBaseSpec.scala, it/helpers/WireMockHelper.scala, it/pages/HelloWorldPageSpec.scala, run.sh, test/controllers/FeatureSwitchControllerSpec.scala, test/testOnly/controllers/FeatureSwitchControllerSpec.scala, test/views/templates/inputs/SingleCheckboxTemplateSpec.scala
i.e.
- scoverage
- readme
- refactoring integration tests
- updating logger config
- refactoring feature switch into test-only routes
=> Updated various parts of repo to bring up to scratch for dereg features

app/views/capitalAssets.scala.html, app/views/deregistrationDate.scala.html, app/views/deregistrationReason.scala.html, app/views/nextTaxableTurnover.scala.html, app/views/optionOwesMoney.scala.html, app/views/optionStocksToSell.scala.html, app/views/vatAccounts.scala.html, app/views/whyTurnoverBelow.scala.html
Also includes some formatting fixes and form-group on stocks page to improve the spacing for error highlighting
=> [BTAT-3747] Add novalidate tag to all forms to disable HTML5 validation

app/controllers/DeregistrationReasonController.scala, test/controllers/DeregistrationReasonControllerSpec.scala, test/services/mocks/MockStoredAnswersService.scala
=> [BTAT-3733] Update DeregReasonController to store and retrieve answers

app/controllers/NextTaxableTurnoverController.scala, app/controllers/TaxableTurnoverController.scala, test/controllers/ControllerBaseSpec.scala, test/controllers/NextTaxableTurnoverControllerSpec.scala, test/controllers/TaxableTurnoverControllerSpec.scala, test/services/mocks/MockStoredAnswersService.scala
**Note**: BTAT-3783 needs merging first.
=> [BTAT-3784] Updated the NextTaxableTurnoverController to store and retrieve answer

app/models/DeregCheckYourAnswersModel.scala
Model added for Check your answers page
=> Model added for Check your answers page

app/controllers/OptionOwesMoneyController.scala, app/controllers/OutstandingInvoicesController.scala, app/services/CapitalAssetsAnswerService.scala, app/services/DeregReasonAnswerService.scala, app/services/OutstandingInvoicesAnswerService.scala, it/pages/OutstandingInvoicesISpec.scala, test/controllers/OptionOwesMoneyControllerSpec.scala, test/controllers/OutstandingInvoicesControllerSpec.scala, test/services/OutstandingInvoicesAnswerServiceSpec.scala, test/services/mocks/MockStoredAnswersService.scala
Also updated routing from OwesMoneyController (which will be refactored to be the 'first' invoice question in later story)
=> Added outstanding-invoices controller 

app/views/vatAccounts.scala.html, conf/messages, test/assets/messages/VATAccountsMessages.scala, test/views/VATAccountsSpec.scala
https://github.com/hmrc/change-vat-acceptance-tests/pull/76
=> [BTAT-3844] content update for VATAccounts page

app/config/ConfigKeys.scala, app/config/frontendAppConfig.scala, app/views/govuk_wrapper.scala.html, conf/application.conf, conf/messages, test/mocks/MockAppConfig.scala
https://github.com/hmrc/app-config-development/pull/1260
https://github.com/hmrc/app-config-qa/pull/2342
https://github.com/hmrc/app-config-staging/pull/1489
https://github.com/hmrc/app-config-production/pull/1956
=> [BTAT-4126] Added feedback URL to contact frontend

app/config/ConfigKeys.scala, app/config/features/Feature.scala, app/config/features/Features.scala, app/config/frontendAppConfig.scala, app/controllers/predicates/AuthoriseAsAgent.scala, app/testOnly/controllers/FeatureSwitchController.scala, app/testOnly/controllers/StubAgentClientLookupController.scala, app/testOnly/forms/FeatureSwitchForm.scala, app/testOnly/forms/StubAgentClientLookupForm.scala, app/testOnly/models/FeatureSwitchModel.scala, app/testOnly/models/StubAgentClientLookupModel.scala, app/testOnly/views/featureSwitch.scala.html, app/testOnly/views/stubAgentClientLookup.scala.html, app/views/templates/inputs/text.scala.html, conf/application.conf, conf/testOnlyDoNotUseInAppConf.routes, test/config/WhitelistFilterSpec.scala, test/config/features/FeaturesSpec.scala, test/controllers/predicates/AuthPredicateSpec.scala, test/controllers/predicates/AuthoriseAsAgentSpec.scala, test/mocks/MockAppConfig.scala, test/utils/TestUtil.scala
**AT PR**
https://github.com/hmrc/change-vat-acceptance-tests/pull/107
**Associated App-Config PRs to support this change**
https://github.com/hmrc/app-config-development/pull/1330
https://github.com/hmrc/app-config-qa/pull/2511
https://github.com/hmrc/app-config-staging/pull/1593
https://github.com/hmrc/app-config-production/pull/2078
=> [BTAT-4337] Add feature switch to stub Agent Client flow and handoff to VACLF

app/views/deregistrationConfirmation.scala.html, project/plugins.sbt
Also corrected other events that didn't match documentation page
=> Added GA event for clicking change client

app/connectors/httpParsers/CustomerDetailsHttpParser.scala, app/connectors/httpParsers/DeregisterVatHttpParser.scala, app/connectors/httpParsers/PendingDeregHttpParser.scala, app/controllers/predicates/PendingChangesPredicate.scala
Some weren't actually errors and some shouldn't have been at WARN level in case of logging sensitive info
=> Tweaked logging levels for errors

app/config/ConfigKeys.scala, app/config/features/Features.scala, app/config/frontendAppConfig.scala, app/testOnly/controllers/FeatureSwitchController.scala, app/testOnly/forms/FeatureSwitchForm.scala, app/testOnly/models/FeatureSwitchModel.scala, app/testOnly/views/featureSwitch.scala.html, app/views/govuk_wrapper.scala.html, build.sbt, conf/application.conf, conf/messages, it/pages/DeregistrationConfirmationISpec.scala, it/pages/VATAccountsISpec.scala, it/stubs/PendingDeregStub.scala, test/connectors/DeregisterVatConnectorSpec.scala, test/mocks/MockAppConfig.scala, test/mocks/MockHttp.scala, test/utils/TestUtil.scala, test/views/GovUkWrapperSpec.scala
https://github.com/hmrc/app-config-base/pull/2512
https://github.com/hmrc/app-config-production/pull/4420
=> Added accessibility statement link to footer of pages

app/config/ConfigKeys.scala, app/config/features/Features.scala, app/testOnly/controllers/FeatureSwitchController.scala, app/testOnly/forms/FeatureSwitchForm.scala, app/testOnly/models/FeatureSwitchModel.scala, app/testOnly/views/featureSwitch.scala.html, build.sbt, conf/application.conf, conf/messages, conf/messages.cy, test/config/features/FeaturesSpec.scala, test/testOnly/controllers/FeatureSwitchControllerSpec.scala, test/utils/TestUtil.scala
=> BTAT-6966 Removed simple auth

app/config/ConfigKeys.scala, app/config/features/Features.scala, app/controllers/DeregistrationConfirmationController.scala, app/testOnly/controllers/FeatureSwitchController.scala, app/testOnly/forms/FeatureSwitchForm.scala, app/testOnly/models/FeatureSwitchModel.scala, app/testOnly/views/featureSwitch.scala.html, app/views/deregistrationConfirmation.scala.html, build.sbt, conf/application.conf, it/pages/DeregistrationConfirmationISpec.scala, test/controllers/DeregistrationConfirmationControllerSpec.scala, test/utils/TestUtil.scala, test/views/DeregistrationConfirmationSpec.scala
=> Removed useContactPreferences feature switch

app/config/ConfigKeys.scala, app/config/features/Features.scala, app/testOnly/controllers/FeatureSwitchController.scala, app/testOnly/forms/FeatureSwitchForm.scala, app/testOnly/models/FeatureSwitchModel.scala, app/testOnly/views/featureSwitch.scala.html, app/views/deregistrationConfirmation.scala.html, conf/application.conf, test/views/DeregistrationConfirmationSpec.scala
=> [DM] [BTAT-7031] Removed changeClient feature switch

app/views/govuk_wrapper.scala.html, build.sbt, test/views/GovUkWrapperSpec.scala
=> BTAT-7132 Remove logo

app/views/govuk_wrapper.scala.html, project/plugins.sbt, public/stylesheets/palette.css
* [X ] Branch is rebased with master
* [ X] Ran `sbt clean compile coverage test it:test coverageReport`, all tests pass and coverage meets minimum
* [ X] Ran [change-vat-acceptance-tests](https://github.com/hmrc/change-vat-acceptance-tests) (see README of repo)
=> BTAT-7141 - Fix for language toggle comes first

app/views/govuk_wrapper.scala.html, public/javascript/errorFocus.js
=> BTAT-7147 Added error focus

app/config/ConfigKeys.scala, app/config/frontendAppConfig.scala, app/views/deregisterForVAT.scala.html, build.sbt, conf/application.conf, project/plugins.sbt, test/mocks/MockAppConfig.scala, test/views/DeregisterForVATSpec.scala
* [y ] Branch is rebased with master
* [y ] Added Unit Tests for changed functionality
* [ y] Ran `sbt clean compile coverage test it:test coverageReport`, all tests pass and coverage meets minimum
* [ y] Checked libraries are up to date with `sbt validate`. (If applicable) library updates are done in a separate, single commit
* [ y] Ran [change-vat-acceptance-tests](https://github.com/hmrc/change-vat-acceptance-tests) (see README of repo)
* [ y] Ran [change-vat-performance-tests](https://github.com/hmrc/change-vat-performance-tests) (see README of repo)
* [y ] (If applicable) raised app-config-* PRs
* [- ] (If applicable) ran Wave test for changes to views
=> updated the back link for dereg journey to point agent hub page

app/controllers/DeregistrationReasonController.scala, app/controllers/zeroRated/BusinessActivityController.scala, app/controllers/zeroRated/PurchasesExceedSuppliesController.scala, app/controllers/zeroRated/SicCodeController.scala, app/controllers/zeroRated/ZeroRatedSuppliesController.scala, app/forms/DeregistrationReasonForm.scala, app/models/DeregistrationReason.scala, app/views/deregistrationReason.scala.html, conf/app.routes, conf/messages, conf/messages.cy, it/pages/DeregistrationReasonISpec.scala, test/assets/messages/DeregistrationReasonMessages.scala, test/controllers/zeroRated/BusinessActivityControllerSpec.scala, test/controllers/zeroRated/PurchasesExceedSuppliesControllerSpec.scala, test/controllers/zeroRated/SicCodeControllerSpec.scala, test/controllers/zeroRated/ZeroRatedSuppliesControllerSpec.scala, test/models/DeregistrationReasonSpec.scala, test/utils/TestUtil.scala, test/views/DeregistrationReasonSpec.scala
**Do not merge, for review only**
**Needs to be rebased off BTAT-7360 to get feature switch and update deregistrationReason view. One test purposefully fails because of this.**
=> Added zero rated as an option to Deregistration Reason page

app/config/ConfigKeys.scala, app/config/frontendAppConfig.scala, app/forms/BusinessActivityForm.scala, app/views/businessActivity.scala.html, conf/application.conf, conf/messages, conf/messages.cy, test/assets/messages/BusinessActivityPageMessages.scala, test/forms/BusinessActivityFormSpec.scala, test/mocks/MockAppConfig.scala, test/views/BusinessActivitySpec.scala
=> [BTAT-7370] - added BusinessActivityView

app/controllers/NextTaxableTurnoverController.scala, test/controllers/NextTaxableTurnoverControllerSpec.scala
=> BTAT-7388 added forward logic into expected taxable turnover page

app/controllers/zeroRated/SicCodeController.scala, conf/messages.cy, it/assets/IntegrationTestConstants.scala, it/pages/SicCodeISpec.scala, project/plugins.sbt, test/controllers/zeroRated/SicCodeControllerSpec.scala, test/services/mocks/MockBusinessActivityAnswerService.scala, test/services/mocks/MockSicCodeAnswerService.scala
=> [BTAT-7377] - SIC Code Page Controller

app/forms/PurchasesExceedSuppliesForm.scala, conf/messages, conf/messages.cy, test/forms/PurchasesExceedSuppliesFormSpec.scala
=> [BTAT-7386] - added purchasesExceedSuppliesForm

app/views/purchasesExceedSupplies.scala.html, test/assets/messages/PurchasesExceedSuppliesMessages.scala, test/views/PurchasesExceedSuppliesSpec.scala
* [ y] Branch is rebased with master
* [ y] Added Unit Tests for changed functionality
* [ y] Ran `sbt clean compile coverage test it:test coverageReport`, all tests pass and coverage meets minimum
* [ y] Checked libraries are up to date with `sbt validate`. (If applicable) library updates are done in a separate, single commit
* [y ] Ran [change-vat-acceptance-tests](https://github.com/hmrc/change-vat-acceptance-tests) (see README of repo)
* [ y] Ran [change-vat-performance-tests](https://github.com/hmrc/change-vat-performance-tests) (see README of repo)
=> Btat 7381- Added Purchase exceed supplies view and test spec

app/controllers/NextTaxableTurnoverController.scala, app/views/nextTaxableTurnover.scala.html, test/controllers/NextTaxableTurnoverControllerSpec.scala, test/controllers/zeroRated/SicCodeControllerSpec.scala, test/services/mocks/MockBusinessActivityAnswerService.scala, test/views/NextTaxableTurnoverSpec.scala
Works against master 
https://jira.tools.tax.service.gov.uk/browse/BTAT-7397 - PR for updated acceptence tests
=> BTAT-7379 updated back logic

app/controllers/zeroRated/PurchasesExceedSuppliesController.scala, it/pages/PurchasesExceedSuppliesISpec.scala, test/controllers/zeroRated/PurchasesExceedSuppliesControllerSpec.scala, test/services/mocks/MockPurchasesExceedSuppliesAnswerService.scala
=> BTAT-7833 updated controller

app/controllers/CapitalAssetsController.scala, app/controllers/CeasedTradingDateController.scala, app/controllers/CheckAnswersController.scala, app/controllers/DeregistrationDateController.scala, app/controllers/DeregistrationReasonController.scala, app/controllers/IssueNewInvoicesController.scala, app/controllers/NextTaxableTurnoverController.scala, app/controllers/OptionStocksToSellController.scala, app/controllers/OptionTaxController.scala, app/controllers/OutstandingInvoicesController.scala, app/controllers/SignOutController.scala, app/controllers/TaxableTurnoverController.scala, app/controllers/VATAccountsController.scala, app/controllers/WhyTurnoverBelowController.scala, app/controllers/zeroRated/BusinessActivityController.scala, app/controllers/zeroRated/PurchasesExceedSuppliesController.scala, app/controllers/zeroRated/SicCodeController.scala, app/controllers/zeroRated/ZeroRatedSuppliesController.scala, project/plugins.sbt
=> [BTAT-6134] - added logging to controllers, refactor in progress

conf/application.conf
=> BTAT-7416: Added xss protection

app/controllers/DeregistrationReasonController.scala, app/controllers/OutstandingInvoicesController.scala, app/controllers/VATAccountsController.scala, app/forms/DeregistrationReasonForm.scala, app/models/DeregistrationReason.scala, app/services/WipeRedundantDataService.scala, app/views/deregistrationReason.scala.html, conf/messages, conf/messages.cy, test/assets/messages/DeregistrationReasonMessages.scala, test/controllers/DeregistrationReasonControllerSpec.scala, test/controllers/OutstandingInvoicesControllerSpec.scala, test/models/DeregistrationReasonSpec.scala, test/views/DeregistrationReasonSpec.scala
=> BTAT-7474 - Update frontend to include ExemptOnly option

conf/messages.cy
=> BTAT-7501 Added missing hidden messages for Welsh

app/views/capitalAssets.scala.html, app/views/issueNewInvoices.scala.html, app/views/optionStocksToSell.scala.html, test/views/CapitalAssetsSpec.scala, test/views/IssueNewInvoicesMoneySpec.scala, test/views/OptionStocksToSellSpec.scala
=> BTAT-7512 - Back links fixed

app/views/capitalAssets.scala.html, app/views/deregistrationDate.scala.html, app/views/optionStocksToSell.scala.html, app/views/optionTax.scala.html, app/views/templates/inputs/text.scala.html, app/views/templates/inputs/yesNoRevealHelper.scala.html, build.sbt, public/stylesheets/vat-v1.css, test/views/CapitalAssetsSpec.scala, test/views/OptionStocksToSellSpec.scala, test/views/OptionTaxSpec.scala, test/views/templates/inputs/TextHelperSpec.scala
=> [BTAT-7519] - edited the yesNo-conditional radio buttons

app/controllers/predicates/PendingChangesPredicate.scala, it/pages/BusinessActivityISpec.scala, it/pages/CheckYourAnswersISpec.scala, it/pages/DeregistrationDateISpec.scala, it/pages/DeregistrationReasonISpec.scala, it/pages/IssueNewInvoicesISpec.scala, it/pages/OutstandingInvoicesISpec.scala, it/pages/PurchasesExceedSuppliesISpec.scala, it/pages/SicCodeISpec.scala, it/pages/VATAccountsISpec.scala, it/pages/WhyTurnoverBelowISpec.scala, it/pages/ZeroRatedSuppliesISpec.scala, test/controllers/predicates/PendingChangesPredicateSpec.scala
=> [BTAT-7526-a] - predicate redirect fix

conf/messages, conf/messages.cy, test/assets/messages/DeregistrationReasonMessages.scala
=> [BTAT-7549] - updated content for the dereg-reason page

app/controllers/zeroRated/BusinessActivityController.scala, app/views/businessActivity.scala.html, app/views/issueNewInvoices.scala.html, app/views/purchasesExceedSupplies.scala.html, test/views/BusinessActivitySpec.scala, test/views/PurchasesExceedSuppliesSpec.scala
=> BTAT-7610 correct invalid ID on form helper in views

public/stylesheets/palette.css
=> BTAT-7634 Updated confirmation h1 box colour

app/views/templates/inputs/dateEntryField.scala.html, conf/messages.cy, public/stylesheets/vat-v1.css
=> BTAT-7738 Welsh content correction for data entry screens

conf/app.routes, conf/prod.routes, it/helpers/IntegrationBaseSpec.scala, it/pages/CheckYourAnswersISpec.scala, it/pages/ChooseDeregistrationDateISpec.scala, it/pages/DeregistrationConfirmationISpec.scala, it/pages/DeregistrationReasonISpec.scala, test/controllers/DeregisterForVATControllerSpec.scala, test/controllers/LanguageControllerSpec.scala
=> [DM] [BTAT-7684] Updated URLs

app/forms/DeregistrationDateForm.scala, test/forms/DeregistrationDateFormSpec.scala
* [X ] Branch is rebased with master
* [X ] Ran [change-vat-acceptance-tests](https://github.com/hmrc/change-vat-acceptance-tests) (see README of repo)
=> BTAT-7739 Add validation to cancellation date form

app/common/Constants.scala, app/controllers/CannotDeregisterThresholdController.scala, app/controllers/CapitalAssetsController.scala, app/controllers/CeasedTradingDateController.scala, app/controllers/CheckAnswersController.scala, app/controllers/ChooseDeregistrationDateController.scala, app/controllers/DeregisterForVATController.scala, app/controllers/DeregistrationDateController.scala, app/controllers/DeregistrationReasonController.scala, app/controllers/IssueNewInvoicesController.scala, app/controllers/NextTaxableTurnoverController.scala, app/controllers/OptionStocksToSellController.scala, app/controllers/OptionTaxController.scala, app/controllers/OutstandingInvoicesController.scala, app/controllers/TaxableTurnoverController.scala, app/controllers/VATAccountsController.scala, app/controllers/WhyTurnoverBelowController.scala, app/controllers/predicates/DeniedAccessPredicate.scala, app/controllers/zeroRated/BusinessActivityController.scala, app/controllers/zeroRated/PurchasesExceedSuppliesController.scala, app/controllers/zeroRated/SicCodeController.scala, app/controllers/zeroRated/ZeroRatedSuppliesController.scala, app/models/CustomerDetails.scala, build.sbt, test/assets/constants/CustomerDetailsTestConstants.scala, test/controllers/ControllerBaseSpec.scala, test/controllers/DeregisterForVATControllerSpec.scala, test/controllers/predicates/DeniedAccessPredicateSpec.scala, test/mocks/MockDeniedAccessPredicate.scala
=> [DM] [BTAT-7695] Added party type check to predicate

app/config/ConfigKeys.scala, app/config/features/Features.scala, app/models/CustomerDetails.scala, app/testOnly/controllers/FeatureSwitchController.scala, app/testOnly/forms/FeatureSwitchForm.scala, app/testOnly/models/FeatureSwitchModel.scala, app/testOnly/views/featureSwitch.scala.html, app/views/deregistrationConfirmation.scala.html, conf/application.conf, conf/messages, conf/messages.cy, conf/testOnlyDoNotUseInAppConf.routes, it/stubs/VatSubscriptionStub.scala, test/assets/constants/CustomerDetailsTestConstants.scala, test/assets/messages/DeregistrationConfirmationMessages.scala, test/views/DeregistrationConfirmationSpec.scala
=> [BTAT-7784] - confirmation messages for agents & customerDetails Reads correction

conf/messages.cy
=> BTAT-7837 Updating  Welsh content on confirmartion screen

app/config/frontendAppConfig.scala
=> [BTAT-7702] Added fix for deprecation warning

app/config/ConfigKeys.scala, app/config/features/Features.scala, app/controllers/DeregistrationConfirmationController.scala, app/models/CustomerDetails.scala, app/testOnly/controllers/FeatureSwitchController.scala, app/testOnly/forms/FeatureSwitchForm.scala, app/testOnly/models/FeatureSwitchModel.scala, app/testOnly/views/FeatureSwitch.scala.html, build.sbt, conf/application.conf, it/pages/DeregistrationConfirmationISpec.scala, it/stubs/VatSubscriptionStub.scala, project/plugins.sbt, test/assets/constants/CustomerDetailsTestConstants.scala, test/controllers/DeregistrationConfirmationControllerSpec.scala
Please ensure this is merged too: https://github.com/hmrc/app-config-production/pull/7511
=> BTAT-8007 Added feature and logic to get comms pref from API#1363

build.sbt
=> Fixed Scoverage settings

app/views/DeregistrationConfirmation.scala.html, conf/messages, conf/messages.cy, test/assets/messages/DeregistrationConfirmationMessages.scala, test/views/DeregistrationConfirmationSpec.scala
=> [BTAT-7902] Removed change client link and updated agent's button text

app/controllers/CheckAnswersController.scala, app/views/CheckYourAnswers.scala.html, test/controllers/CheckAnswersControllerSpec.scala, test/views/CheckYourAnswersSpec.scala
=> BTAT-8204 - Removed CYA back link

app/views/GovukWrapper.scala.html, public/javascript/errorFocus.js
* [X ] Branch is rebased with master
* [X ] Ran `sbt clean compile coverage test it:test coverageReport`, all tests pass and coverage meets minimum
* [X ] Ran [change-vat-acceptance-tests](https://github.com/hmrc/change-vat-acceptance-tests) (see README of repo)
=> BTAT-8265 Fix in error.js

app/config/ConfigKeys.scala, app/config/frontendAppConfig.scala, app/views/GovukWrapper.scala.html, app/views/MainTemplate.scala.html, conf/application.conf, run.sh, test/mocks/MockAppConfig.scala
=> [BTAT-8278] Removed GTM and GA snippets

build.sbt, it/helpers/SessionCookieBaker.scala, project/build.properties
=> BTAT-8310 - removed deprecated auth session keys

project/build.properties
=> BTAT-8310 - revert version change

app/forms/DateForm.scala, app/views/templates/errors/ErrorSummary.scala.html, app/views/templates/inputs/Date.scala.html, test/assets/messages/CommonMessages.scala, test/views/CeasedTradingDateSpec.scala, test/views/CheckYourAnswersSpec.scala, test/views/DeregistrationDateSpec.scala
=> [BTAT-8246] WCAG - Issue: Date error messages

app/views/templates/inputs/CheckboxHelper.scala.html, app/views/templates/inputs/Date.scala.html, app/views/templates/inputs/MultipleLineRadioGroup.scala.html, app/views/templates/inputs/RadioHelper.scala.html, app/views/templates/inputs/Text.scala.html, test/views/BusinessActivitySpec.scala, test/views/CapitalAssetsSpec.scala, test/views/ChooseDeregistrationDateSpec.scala, test/views/DeregistrationReasonSpec.scala, test/views/OptionTaxSpec.scala, test/views/PurchasesExceedSuppliesSpec.scala, test/views/SicCodeSpec.scala, test/views/VATAccountsSpec.scala, test/views/templates/inputs/CheckboxHelperSpec.scala, test/views/templates/inputs/MultipleLineRadioGroupTemplateSpec.scala, test/views/templates/inputs/RadioGroupTemplateSpec.scala, test/views/templates/inputs/TextHelperSpec.scala
This reverts commit 98d1939fc43d6930d6f1929a161ef59787157303, reversing
changes made to 62583ff2402debb4b1729ca55282502569c34f36.
=> Revert "Merge remote-tracking branch 'origin/BTAT-8320'"

app/views/templates/inputs/Text.scala.html, test/views/templates/inputs/TextHelperSpec.scala
=> BTAT-8509 Updating label for monetary input boxes

app/config/ConfigKeys.scala, app/config/frontendAppConfig.scala, app/views/GovukWrapper.scala.html, build.sbt, conf/application.conf, project/plugins.sbt, test/mocks/MockAppConfig.scala
* [ x] Branch is rebased with master
* [x ] Added Unit Tests for changed functionality
* [ x] Ran `sbt clean compile coverage test it:test coverageReport`, all tests pass and coverage meets minimum
* [ x] Ran [change-vat-acceptance-tests](https://github.com/hmrc/change-vat-acceptance-tests) (see README of repo)
=> [BTAT-8596] Updated tracking consent script

app/config/frontendAppConfig.scala, build.sbt, conf/application.conf
=> BTAT-8651 Replaced sign out URLs with bas-gateway counterparts

app/controllers/SignOutController.scala, app/models/CustomerDetails.scala, app/views/GovukWrapper.scala.html, build.sbt, test/assets/constants/CustomerDetailsTestConstants.scala, test/controllers/SignOutControllerSpec.scala, test/models/CustomerDetailsModelSpec.scala
=> Btat 8942 Updated model

app/forms/ZeroRatedSuppliesForm.scala, app/views/ZeroRatedSupplies.scala.html, it/pages/ZeroRatedSuppliesISpec.scala, test/controllers/zeroRated/ZeroRatedSuppliesControllerSpec.scala, test/forms/ZeroRatedSuppliesFormSpec.scala
=> [BTAT-8985] WCAG: Corrected link ID in error summary

app/controllers/SignOutController.scala, app/views/MainTemplate.scala.html, app/views/errors/agent/Unauthorised.scala.html, app/views/errors/client/Unauthorised.scala.html, test/controllers/SignOutControllerSpec.scala
=> [BTAT-8965] - updated sign-out method for unauthorised users

build.sbt, public/stylesheets/vat-v1.css
=> [BTAT-9007] WCAG: Updated CSS to hide menu toggle

app/forms/DateForm.scala, app/views/templates/errors/ErrorSummary.scala.html, app/views/templates/inputs/Date.scala.html, conf/messages, conf/messages.cy, test/assets/messages/CommonMessages.scala, test/views/CeasedTradingDateSpec.scala, test/views/DeregistrationDateSpec.scala
=> BTAT-9049 Updated day/month/year error messages for date inputs

app/config/ConfigKeys.scala, app/config/features/Features.scala, app/testOnly/controllers/FeatureSwitchController.scala, app/testOnly/forms/FeatureSwitchForm.scala, app/testOnly/models/FeatureSwitchModel.scala, app/testOnly/views/FeatureSwitch.scala.html, app/views/DeregistrationConfirmation.scala.html, conf/application.conf, conf/messages, conf/messages.cy, test/assets/messages/DeregistrationConfirmationMessages.scala, test/views/DeregistrationConfirmationSpec.scala
=> [BTAT-9179] - Removal of bulkPaperOffFeature.enabled feature switch

app/config/ConfigKeys.scala, app/config/features/Features.scala, app/controllers/DeregistrationConfirmationController.scala, app/testOnly/controllers/FeatureSwitchController.scala, app/testOnly/forms/FeatureSwitchForm.scala, app/testOnly/models/FeatureSwitchModel.scala, app/testOnly/views/FeatureSwitch.scala.html, conf/application.conf, test/controllers/DeregistrationConfirmationControllerSpec.scala
=> BTAT-9178 remove emailVerifiedFeature

app/config/ConfigKeys.scala, app/config/features/Features.scala, app/controllers/zeroRated/BusinessActivityController.scala, app/controllers/zeroRated/PurchasesExceedSuppliesController.scala, app/controllers/zeroRated/SicCodeController.scala, app/controllers/zeroRated/ZeroRatedSuppliesController.scala, app/testOnly/controllers/FeatureSwitchController.scala, app/testOnly/forms/FeatureSwitchForm.scala, app/testOnly/models/FeatureSwitchModel.scala, app/testOnly/views/FeatureSwitch.scala.html, conf/application.conf, test/controllers/zeroRated/BusinessActivityControllerSpec.scala, test/controllers/zeroRated/PurchasesExceedSuppliesControllerSpec.scala, test/controllers/zeroRated/SicCodeControllerSpec.scala, test/controllers/zeroRated/ZeroRatedSuppliesControllerSpec.scala, test/utils/TestUtil.scala
=> [BTAT-9177]- Removed Zero Rate Journey Feature Switch and all traces of it being used

app/config/ConfigKeys.scala, app/config/features/Features.scala, app/testOnly/controllers/FeatureSwitchController.scala, app/testOnly/forms/FeatureSwitchForm.scala, app/testOnly/models/FeatureSwitchModel.scala, app/testOnly/views/FeatureSwitch.scala.html, build.sbt, conf/application.conf, conf/messages, conf/messages.cy, project/plugins.sbt, test/utils/TestUtil.scala
=> Btat 9174 Removed useLanguageSelector feature switch

app/config/ConfigKeys.scala, app/config/features/Features.scala, app/config/frontendAppConfig.scala, app/testOnly/controllers/FeatureSwitchController.scala, app/testOnly/forms/FeatureSwitchForm.scala, app/testOnly/models/FeatureSwitchModel.scala, app/testOnly/views/FeatureSwitch.scala.html, conf/application.conf, test/mocks/MockAppConfig.scala, test/utils/TestUtil.scala
App Config QA  -> https://github.com/hmrc/app-config-qa/pull/11448
=> [BTAT-9181]-Removal of Stub Contact Preferences feature

app/views/BusinessActivity.scala.html, app/views/CannotDeregisterThreshold.scala.html, app/views/CapitalAssets.scala.html, app/views/CeasedTradingDate.scala.html, app/views/ChooseDeregistrationDate.scala.html, app/views/DeregisterForVAT.scala.html, app/views/DeregistrationDate.scala.html, app/views/DeregistrationReason.scala.html, app/views/IssueNewInvoices.scala.html, app/views/MainTemplate.scala.html, app/views/NextTaxableTurnover.scala.html, app/views/OptionStocksToSell.scala.html, app/views/OptionTax.scala.html, app/views/OutstandingInvoices.scala.html, app/views/PurchasesExceedSupplies.scala.html, app/views/SicCode.scala.html, app/views/TaxableTurnover.scala.html, app/views/VatAccounts.scala.html, app/views/WhyTurnoverBelow.scala.html, app/views/ZeroRatedSupplies.scala.html, build.sbt, project/plugins.sbt, test/views/DeregisterForVATSpec.scala
* [ x Ran [change-vat-acceptance-tests](https://github.com/hmrc/change-vat-acceptance-tests) (see README of repo)
=> BTAT-9385 - Moving back link out of main content

app/assets/stylesheets/application.scss, app/views/MainTemplate.scala.html, build.sbt, conf/messages, conf/messages.cy
=> BTAT-9434 - Updated deregister vat frontend with HMRC Standard Header

app/testOnly/views/StubAgentClientLookup.scala.html, conf/application.conf
Please merge this first to keep the stub redirection disabled in QA and Staging: https://github.com/hmrc/app-config-base/pull/6028
=> BTAT-9577 Toggled stubAgentClientLookup switch for local use

conf/application.conf
=> Replaced contentSecurityPolicy by CSPFilter in application.conf

app/assets/stylesheets/application.scss, app/config/ConfigKeys.scala, app/config/frontendAppConfig.scala, app/views/MainTemplate.scala.html, app/views/utils/ServiceNameUtil.scala, build.sbt, conf/application.conf, project/plugins.sbt, test/mocks/MockAppConfig.scala, test/views/MainTemplateSpec.scala, test/views/utils/ServiceNameUtilSpec.scala
=> Btat 9596 Added link to service name in header

build.sbt
=> [BTAT-9643] Removed play-frontend-govuk

app/views/templates/inputs/DateHelper.scala.html, app/views/utils/DateErrorHelper.scala, build.sbt, test/views/MainTemplateSpec.scala, test/views/errors/agent/UnauthorisedViewSpec.scala, test/views/errors/client/UnauthorisedViewSpec.scala, test/views/templates/inputs/DateHelperSpec.scala, test/views/utils/DateErrorHelperSpec.scala
=> Btat 9690 Applied error style to date fields

app/forms/NextTaxableTurnoverForm.scala, app/forms/YesNoAmountForm.scala, app/forms/ZeroRatedSuppliesForm.scala, app/forms/utils/FormValidation.scala, test/forms/NextTaxableTurnoverFormSpec.scala, test/forms/YesNoAmountFormSpec.scala, test/forms/ZeroRatedSuppliesFormSpec.scala, test/forms/utils/FormValidationSpec.scala
=> BTAT-9692 fix field validation for generic formatting

app/config/frontendAppConfig.scala, app/controllers/DeregisterForVATController.scala, app/controllers/DeregistrationConfirmationController.scala, app/controllers/predicates/DeniedAccessPredicate.scala, app/views/DeregistrationReason.scala.html, conf/app.routes, it/pages/BusinessActivityISpec.scala, it/pages/CheckYourAnswersISpec.scala, it/pages/ChooseDeregistrationDateISpec.scala, it/pages/DeregistrationDateISpec.scala, it/pages/DeregistrationReasonISpec.scala, it/pages/IssueNewInvoicesISpec.scala, it/pages/OutstandingInvoicesISpec.scala, it/pages/PurchasesExceedSuppliesISpec.scala, it/pages/SicCodeISpec.scala, it/pages/VATAccountsISpec.scala, it/pages/WhyTurnoverBelowISpec.scala, it/pages/ZeroRatedSuppliesISpec.scala, test/controllers/DeregisterForVATControllerSpec.scala, test/controllers/DeregistrationConfirmationControllerSpec.scala, test/controllers/predicates/DeniedAccessPredicateSpec.scala, test/views/DeregistrationReasonSpec.scala
=> [BTAT-9840] - Removed user type from routing and updated url for dereg-vat-fe

app/models/CustomerDetails.scala, app/services/UpdateDeregistrationService.scala, build.sbt, test/controllers/zeroRated/SicCodeControllerSpec.scala, test/forms/DeregistrationReasonFormSpec.scala, test/forms/YesNoAmountFormSpec.scala, test/models/deregistrationRequest/DeregistrationInfoSpec.scala, test/services/UpdateDeregistrationServiceSpec.scala, test/services/WipeRedundantDataServiceSpec.scala
=> Btat 9878 Added missing unit tests

app/config/ConfigKeys.scala, app/config/frontendAppConfig.scala, app/views/MainTemplate.scala.html, conf/application.conf, test/mocks/MockAppConfig.scala
=> [BTAT-10011]-Updated accessibility statement

.bsp/sbt.json, .gitignore, build.sbt, project/build.properties, project/plugins.sbt
=> [BTAT-10110] Upgrade to sbt 1.4 and other dependency upgrades

app/config/ConfigKeys.scala, app/config/frontendAppConfig.scala, app/views/MainTemplate.scala.html, build.sbt, conf/application.conf, test/mocks/MockAppConfig.scala
=> BTAT-10127 Switch to hmrcReportTechnicalIssueHelper and sbt upgrade

app/views/CheckYourAnswers.scala.html, test/views/CheckYourAnswersSpec.scala
=> [BTAT-10142] Added prevent double click attribute to CYA button

build.sbt, test/views/templates/errors/ErrorSummaryHelperSpec.scala, test/views/templates/inputs/DateHelperSpec.scala, test/views/templates/inputs/YesNoHelperSpec.scala, test/views/templates/inputs/YesNoRevealHelperSpec.scala
=> [BTAT-10403] - PR to revert changes for play-frontend-hmrc plugin

build.sbt
https://confluence.tools.tax.service.gov.uk/display/TEC/2022/06/14/AppSec+nagging+about+test+stowaways
=> Set appropriate scope for bootstrap test

app/models/DateModel.scala, build.sbt, it/helpers/IntegrationBaseSpec.scala, it/pages/DeregistrationConfirmationISpec.scala, project/plugins.sbt, test/controllers/predicates/DeniedAccessPredicateSpec.scala, test/models/DateModelSpec.scala, test/utils/TestUtil.scala, test/views/ViewBaseSpec.scala
=> [BTAT-11073] Scala 2.13 upgrade

README.md
=> [BTAT-11160] Update readme to refer to run.sh script

app/controllers/VATAccountsController.scala, app/forms/DateForm.scala, app/forms/VATAccountsForm.scala, build.sbt
=> [BTAT-11421] Addressed compilation warnings

app/common/Constants.scala
=> BTAT-11480 Removing TODO in Constants file

app/audit/models/DeregStartAuditModel.scala, app/audit/models/DeregSuccessAuditModel.scala, app/audit/services/AuditService.scala, app/controllers/DeregisterForVATController.scala, app/services/UpdateDeregistrationService.scala, build.sbt, test/audit/models/DeregStartAuditModelSpec.scala, test/audit/models/DeregSuccessAuditModelSpec.scala, test/audit/services/AuditServiceSpec.scala, test/controllers/DeregisterForVATControllerSpec.scala, test/services/UpdateDeregistrationServiceSpec.scala, test/services/mocks/MockAuditService.scala
=> Btat 11518 Adding new audit events

app/views/MainTemplate.scala.html
=> [BTAT-11501] Removing beta phase banner

app/config/ConfigKeys.scala, app/config/features/Features.scala, app/config/frontendAppConfig.scala, app/testOnly/controllers/FeatureSwitchController.scala, app/testOnly/forms/FeatureSwitchForm.scala, app/testOnly/models/FeatureSwitchModel.scala, app/testOnly/views/FeatureSwitch.scala.html, app/views/DeregisterForVAT.scala.html, conf/application.conf, conf/messages, conf/messages.cy, it/pages/WhyTurnoverBelowISpec.scala, test/controllers/NextTaxableTurnoverControllerSpec.scala, test/mocks/MockAppConfig.scala, test/views/DeregisterForVATSpec.scala
=> DL-13384  Deregister for VAT- View & Change webchat

build.sbt, conf/logback.xml, project/build.properties, project/plugins.sbt, test/connectors/mocks/MockVatSubscriptionConnector.scala, test/services/mocks/MockCustomerDetailsService.scala
=> DL- 16012 remove unused dependencies and trigger PR bot comments
